/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsActiveRouteImport } from './routes/jobs.active'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsNewIndexRouteImport } from './routes/jobs.new.index'
import { Route as JobsNewVehicleRouteImport } from './routes/jobs.new.vehicle'
import { Route as JobsNewComplaintRouteImport } from './routes/jobs.new.complaint'
import { Route as JobsJobIdInvoiceRouteImport } from './routes/jobs.$jobId_.invoice'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsActiveRoute = JobsActiveRouteImport.update({
  id: '/jobs/active',
  path: '/jobs/active',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewIndexRoute = JobsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsNewRoute,
} as any)
const JobsNewVehicleRoute = JobsNewVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => JobsNewRoute,
} as any)
const JobsNewComplaintRoute = JobsNewComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => JobsNewRoute,
} as any)
const JobsJobIdInvoiceRoute = JobsJobIdInvoiceRouteImport.update({
  id: '/jobs/$jobId_/invoice',
  path: '/jobs/$jobId/invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/new': typeof JobsNewRouteWithChildren
  '/jobs/$jobId/invoice': typeof JobsJobIdInvoiceRoute
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new/': typeof JobsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/$jobId/invoice': typeof JobsJobIdInvoiceRoute
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new': typeof JobsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/new': typeof JobsNewRouteWithChildren
  '/jobs/$jobId_/invoice': typeof JobsJobIdInvoiceRoute
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new/': typeof JobsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/$jobId'
    | '/jobs/active'
    | '/jobs/new'
    | '/jobs/$jobId/invoice'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/$jobId'
    | '/jobs/active'
    | '/jobs/$jobId/invoice'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/$jobId'
    | '/jobs/active'
    | '/jobs/new'
    | '/jobs/$jobId_/invoice'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  WorkshopRoute: typeof WorkshopRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsActiveRoute: typeof JobsActiveRoute
  JobsNewRoute: typeof JobsNewRouteWithChildren
  JobsJobIdInvoiceRoute: typeof JobsJobIdInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/active': {
      id: '/jobs/active'
      path: '/jobs/active'
      fullPath: '/jobs/active'
      preLoaderRoute: typeof JobsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new/': {
      id: '/jobs/new/'
      path: '/'
      fullPath: '/jobs/new/'
      preLoaderRoute: typeof JobsNewIndexRouteImport
      parentRoute: typeof JobsNewRoute
    }
    '/jobs/new/vehicle': {
      id: '/jobs/new/vehicle'
      path: '/vehicle'
      fullPath: '/jobs/new/vehicle'
      preLoaderRoute: typeof JobsNewVehicleRouteImport
      parentRoute: typeof JobsNewRoute
    }
    '/jobs/new/complaint': {
      id: '/jobs/new/complaint'
      path: '/complaint'
      fullPath: '/jobs/new/complaint'
      preLoaderRoute: typeof JobsNewComplaintRouteImport
      parentRoute: typeof JobsNewRoute
    }
    '/jobs/$jobId_/invoice': {
      id: '/jobs/$jobId_/invoice'
      path: '/jobs/$jobId/invoice'
      fullPath: '/jobs/$jobId/invoice'
      preLoaderRoute: typeof JobsJobIdInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsNewRouteChildren {
  JobsNewComplaintRoute: typeof JobsNewComplaintRoute
  JobsNewVehicleRoute: typeof JobsNewVehicleRoute
  JobsNewIndexRoute: typeof JobsNewIndexRoute
}

const JobsNewRouteChildren: JobsNewRouteChildren = {
  JobsNewComplaintRoute: JobsNewComplaintRoute,
  JobsNewVehicleRoute: JobsNewVehicleRoute,
  JobsNewIndexRoute: JobsNewIndexRoute,
}

const JobsNewRouteWithChildren =
  JobsNewRoute._addFileChildren(JobsNewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  WorkshopRoute: WorkshopRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsActiveRoute: JobsActiveRoute,
  JobsNewRoute: JobsNewRouteWithChildren,
  JobsJobIdInvoiceRoute: JobsJobIdInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
