/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsActiveRouteImport } from './routes/jobs.active'
import { Route as JobsNewIndexRouteImport } from './routes/jobs.new.index'
import { Route as JobsNewVehicleRouteImport } from './routes/jobs.new.vehicle'
import { Route as JobsNewComplaintRouteImport } from './routes/jobs.new.complaint'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsActiveRoute = JobsActiveRouteImport.update({
  id: '/jobs/active',
  path: '/jobs/active',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewIndexRoute = JobsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsNewRoute,
} as any)
const JobsNewVehicleRoute = JobsNewVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => JobsNewRoute,
} as any)
const JobsNewComplaintRoute = JobsNewComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => JobsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/new': typeof JobsNewRouteWithChildren
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new/': typeof JobsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new': typeof JobsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workshop': typeof WorkshopRoute
  '/jobs/active': typeof JobsActiveRoute
  '/jobs/new': typeof JobsNewRouteWithChildren
  '/jobs/new/complaint': typeof JobsNewComplaintRoute
  '/jobs/new/vehicle': typeof JobsNewVehicleRoute
  '/jobs/new/': typeof JobsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/active'
    | '/jobs/new'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/active'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/workshop'
    | '/jobs/active'
    | '/jobs/new'
    | '/jobs/new/complaint'
    | '/jobs/new/vehicle'
    | '/jobs/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  WorkshopRoute: typeof WorkshopRoute
  JobsActiveRoute: typeof JobsActiveRoute
  JobsNewRoute: typeof JobsNewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/active': {
      id: '/jobs/active'
      path: '/jobs/active'
      fullPath: '/jobs/active'
      preLoaderRoute: typeof JobsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new/': {
      id: '/jobs/new/'
      path: '/'
      fullPath: '/jobs/new/'
      preLoaderRoute: typeof JobsNewIndexRouteImport
      parentRoute: typeof JobsNewRoute
    }
    '/jobs/new/vehicle': {
      id: '/jobs/new/vehicle'
      path: '/vehicle'
      fullPath: '/jobs/new/vehicle'
      preLoaderRoute: typeof JobsNewVehicleRouteImport
      parentRoute: typeof JobsNewRoute
    }
    '/jobs/new/complaint': {
      id: '/jobs/new/complaint'
      path: '/complaint'
      fullPath: '/jobs/new/complaint'
      preLoaderRoute: typeof JobsNewComplaintRouteImport
      parentRoute: typeof JobsNewRoute
    }
  }
}

interface JobsNewRouteChildren {
  JobsNewComplaintRoute: typeof JobsNewComplaintRoute
  JobsNewVehicleRoute: typeof JobsNewVehicleRoute
  JobsNewIndexRoute: typeof JobsNewIndexRoute
}

const JobsNewRouteChildren: JobsNewRouteChildren = {
  JobsNewComplaintRoute: JobsNewComplaintRoute,
  JobsNewVehicleRoute: JobsNewVehicleRoute,
  JobsNewIndexRoute: JobsNewIndexRoute,
}

const JobsNewRouteWithChildren =
  JobsNewRoute._addFileChildren(JobsNewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  WorkshopRoute: WorkshopRoute,
  JobsActiveRoute: JobsActiveRoute,
  JobsNewRoute: JobsNewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
