// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfycncvtndfscahvvixv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeWNuY3Z0bmRmc2NhaHZ2aXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4MDEyNDAsImV4cCI6MjA5NDM3NzI0MH0.6dhxvpht-ZklQ9kW5QPbVRchtyIwjr5u3t_G14980EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});